-- V4__notifications.sql
-- Adds the notification table for user-scoped notifications (e.g. AI recommendation
-- run completion), and a user FK on ai_recommendation_runs so the result consumer
-- can target the originating user without a JOIN through the createdBy email.

-- 1. notification table
CREATE TABLE "public"."notification" (
    "id"            bigint NOT NULL,
    "user_id"       bigint NOT NULL,
    "type"          character varying(64) NOT NULL,
    "title"         character varying(255) NOT NULL,
    "message"       text,
    "reference_id"  character varying(255),
    "link_url"      character varying(512),
    "severity"      character varying(32) NOT NULL DEFAULT 'INFO',
    "is_read"       boolean NOT NULL DEFAULT false,
    "created_at"    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "read_at"       timestamp with time zone,
    "created_by"    character varying(255),
    "updated_at"    timestamp without time zone,
    "updated_by"    character varying(255)
);

ALTER TABLE "public"."notification"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."notification_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE ONLY "public"."notification"
    ADD CONSTRAINT "notification_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."notification"
    ADD CONSTRAINT "notification_user_fkey"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

CREATE INDEX "idx_notification_user_unread"
    ON "public"."notification" ("user_id", "is_read", "created_at" DESC);

CREATE INDEX "idx_notification_user_created"
    ON "public"."notification" ("user_id", "created_at" DESC);

-- 2. ai_recommendation_runs.created_by_user_id
ALTER TABLE "public"."ai_recommendation_runs"
    ADD COLUMN "created_by_user_id" bigint;

ALTER TABLE ONLY "public"."ai_recommendation_runs"
    ADD CONSTRAINT "ai_recommendation_runs_created_by_user_fkey"
    FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL;

CREATE INDEX "idx_ai_runs_created_by_user"
    ON "public"."ai_recommendation_runs" ("created_by_user_id", "created_at" DESC);
